### ISSUE TITLE
Googlesheets

### ISSUE THREAD

**Issue by dieza** [benmarwick/ctv-archaeology#16]
There is a typo in the 'googlesheets' packages, both in the link and in the text is written as 'googlesheet' instead of **googlesheets**
https://github.com/jennybc/googlesheets
The opposite is true in **ggmap** that appears like ggmaps instead of 'ggmap' in the text and in the linked URL

**Comment by benmarwick** [comment]
Thanks for spotting those. Would you like to make a pull request to fix them, so we can add you as a contributor?

**Comment by dieza** [comment]
Ben,
I’m already a more than happy contributor [1], but maybe I have to github accounts. By the way, if you have not objection, I’m planning to do a Spanish version of your github.
Cheers and thanks for gathering all these gems.
Agustín
 [1] Agustín Diez Castillo

**Comment by dieza** [comment]
Ben,
That means that we are a bunch of contibrutors ;-), that it’s great. I will keep up you updated with the Spanish version.
Cheers.
Agustín
