### ISSUE TITLE
Add mapsf package ?

### ISSUE THREAD

**Issue by JGravier** [benmarwick/ctv-archaeology#33]
Hello @benmarwick,

I think the new (and very cool !) [mapsf package](http://cran.r-project.org/web/packages/mapsf/index.html) could be added to the list of useful packages for making maps easily and quickly.

I take this "issue" opportunity to thank you for this Task View always at the top !

**Comment by benmarwick** [comment]
Yes, what a great find, thank you so much! It is a very cool pkg. I have merged your PR. Thank you again!
