### ISSUE TITLE
ggvis in the visualization section?

### ISSUE THREAD

**Issue by sfsheath** [benmarwick/ctv-archaeology#4]
http://ggvis.rstudio.com . I haven't quite replaced ggplot2 in my own work but have had good experiences mucking about with ggvis.

**Comment by benmarwick** [comment]
Interesting suggestion, I've fiddled with it a bit also and been a bit unsatisfied at how non-trivial it is to get mouse-over tooltips on data points, and how it has to be connected to a running R session to get interactivity (I want a static, stand-alone HTML doc with plots that have mouse-over tooltips... seems that rCharts is to the simplest way to get that at the moment). I look forward to the next major release to see if it will become more compelling. I've added it nonetheless, thanks again for the suggestion.
