### ISSUE TITLE
Make the repository citable

### ISSUE THREAD

**Issue by EstherPlomp** [benmarwick/ctv-archaeology#48]
Hi Ben! 

I would love to cite the repository in a contribution: would it be possible to link the repository with Zenodo (for example) and get a DOI for a new release? Perhaps you're already familiar with the process, but just to be sure there's some documentation on the workflow here: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content. 

Or, include a suggested citation for the repository in the readme file? 

Thank you!

**Comment by benmarwick** [comment]
Hey, thanks for this suggestion, that is a great idea! I've done it now.
