### ISSUE TITLE
Minor revisions of the CTV draft

### ISSUE THREAD

**Issue by nfrerebeau** [benmarwick/ctv-archaeology#58]
@benmarwick I'd like to suggest a few modifications of the CTV draft:

* Add `aion` to the "chronology" section.
* Link to the CRAN version of `era`.
* Move `SPARTAAS` to the "chronology" section.
* Replace `tesselle/fasti` with `ArchaeoStat/ArchaeoData`.
* Remove `nexus` (initial development is in progress).

If that sounds OK, I can make a PR with the modifications.

**Comment by benmarwick** [comment]
These look great to me, thanks so much! 

Now that our group of co-maintainers is stable and, I think, complete, I will invite everyone to share their thoughts and to 'watch' this repo to get notifications of activity, and join is the discussion as you like (completely voluntary and optional, if you are busy or have no opinion on a particular issue, no need to reply to anything, that is fine): @scpederzani @SCSchmidt @lolosp @lsteinmann @LiYingWang @bbartholdy @joeroe @nfrerebeau

**Comment by nfrerebeau** [comment]
I got the following after running `ctv::check_ctv_packages()`:

* `zooaRch` is [archived on CRAN since 2023-08-18](https://cran.r-project.org/package=zooaRch). I couldn't find the package code repository.
* `rysgran` is [archived on CRAN since 2021-02-05](https://cran.r-project.org/package=rysgran). It seems that a new version is under preparation [here](https://github.com/mauricio-camargo/rysgran).

I don't know which [action](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md#cran-package-archivals) is best. Perhaps these two packages could be removed while the CTV is being submitted?

**Comment by benmarwick** [comment]
@nfrerebeau thanks for running that check and reporting the results. I've removed zooaRch and changed rysgran to the github pkg. Thanks again!
